<section class="content-header">
    <nav class="module navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"><i class="fa fa-cogs"></i> Site config</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Scope 1</a></li>
                <li><a href="#">Scope 2</a></li>
                <li><a href="#">Scope 3</a></li>
            </ul>
        </div>
    </nav>
</section>