<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<section class="content-header">
    <h1><i class="fa fa-cogs"></i> Site config. <?=$viewModel->getScope()->getName()?></h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-body">
                    <?php if ($viewModel->getCollection()->count()): ?>
                        <form role="form" id="config-values">
                            <?php foreach ($viewModel->getCollection() as $value): ?>
                                <?= $this->partial('t4web-site-config/partials/admin-config-value.phtml', ['name' => $value->getName(), 'value' => $value->getValue()]) ?>
                            <?php endforeach; ?>
                        </form>
                    <?php else: ?>
                        <p>Config entries does not exists</p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</section>

<?php $this->headScript()->captureStart() ?>
$(function () {
    $('#config-values button').click(function () {
        var $input = $(this).parent().parent().find('input');
        var $formGroup = $(this).parent().parent().parent();

        $.ajax({
            url: '/admin/site-config/save',
            type: 'POST',
            data: {
                name: $input.attr('name'),
                value: $input.val()
            },
            success: function (response) {
                $formGroup.addClass('has-success');
                $formGroup.find('label').append(' <i class="fa fa-check"></i> Saved');
                setTimeout(
                    function(){
                        $formGroup.removeClass('has-success');
                        var label = $formGroup.find('label').html();
                        $formGroup.find('label').html(label.replace(' <i class="fa fa-check"></i> Saved', ''));
                    },
                    3000
                );
            },
            error: function (response) {
                alert(response.message);
            }
        });
    });
});
<?php $this->headScript()->captureEnd() ?>
