<?php $this->headScript()->appendFile($this->basePath() . '/adm/js/site-config/show.js');?>

<?php $viewModel = $this->viewModel()->getCurrent(); ?>
<?= $this->partial('site-config/partials/admin-menu.phtml',
    ['scopes' => $viewModel->getScopes(), 'viewModel' => $viewModel]) ?>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-body">
                    <form role="form">
                        <?php foreach($viewModel->getValues() as $value): ?>
                            <?= $this->partial('site-config/partials/admin-config-value.phtml',
                                ['label' => $value->getName(), 'value' => $value->getValue()]) ?>
                        <?php endforeach; ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
