<?= $this->partial('site-config/partials/admin-menu.phtml') ?>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-body">

                    <form role="form">

                        <div class="form-group">
                            <label>Text</label>
                            <div class="input-group">
                                <input type="text" class="form-control">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-info btn-flat"><i class="fa fa-save"></i> Save</button>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Text</label>
                            <div class="input-group">
                                <input type="text" class="form-control">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-info btn-flat"><i class="fa fa-save"></i> Save</button>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Text</label>
                            <div class="input-group">
                                <input type="text" class="form-control">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-info btn-flat"><i class="fa fa-save"></i> Save</button>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Text</label>
                            <div class="input-group">
                                <input type="text" class="form-control">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-info btn-flat"><i class="fa fa-save"></i> Save</button>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Text</label>
                            <div class="input-group">
                                <input type="text" class="form-control">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-info btn-flat"><i class="fa fa-save"></i> Save</button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
